#!/bin/bash

paths=/Users/$MISTRESS/temp/mediaTemp

function rehashFile()
{
    # path=$1   # 递归中不应赋值
    if [ -d $1 ]; then
        for subPath in `ls $1`
        do
            rehashFile $1/$subPath
        done
    elif [ -f $1 ]; then
        echo "rehash $1 successful"
        echo 0 >> $1
    else
        echo "not support $1"
    fi
}

if [ $# -gt 0 ]; then
    paths=$*
fi

IFS=$'\t'   # 修改for...in的分隔符，避免解析不了含空格的文件
for path in $paths
do
    rehashFile $path
done
